config/routes.rb
################################################################################
#   29.03.2018  Bug fixed for logout error (is it since Rails 5.2?):
#               No route matches [GET] "/ru/logout" 
#               Solution: *get* instead of *delete*  - has been canceled (see below)
#               Later: The bug is vanishing if to use *jquery_ujs* - MUST BE!
#   01.11.2020  Active Storage added for redirection
#   02.11.2020  DRY code
#   07.12.2020  Fixing Error: No route matches [GET] “/logout”
#   16.03.2022  Rails 7
################################################################################
Rails.application.routes.draw do

  app_scope = MULTILINGUAL ? "/:locale" : "/"
  scope app_scope, locale: /#{I18n.available_locales.join("|")}/ do

    # Session resources
    get    'sessions/new'                                # sessions_new_path
    post   'login',  to: 'sessions#create'               # login_path  - creates new session (login)
    get    'logout', to: 'sessions#destroy', as: :logout # logout_path - destroys    session (log out)
  # delete 'logout', to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                 # admin_root_path
      resources :users
      resources :samples
      resources :coins
      resources :coin_nicknames
      resources :pairs
      resources :pair_nicknames
      # Add new admin resources before this line
    end

    root      'pages#home'                               # root_path
    get :demo, to: 'pages#demo', path: 'demo'
    resources  :samples
  end

  if MULTILINGUAL
    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
  
    # Active Storage paths are excluded from the redirection process
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(rails\/active_storage|#{I18n.available_locales.join("|")})\/).*/}, format: false
  end
end

app/models/pair.rb
################################################################################
# Model:  Pair
#
# Purpose:
#
# Pair attributes:
#   base_id         - FK
#   quote_id        - FK
#   name            - string,  not NULL, unique
#   code            - string
#   level           - Liquidity Level: enum { Major (0) | Minor (1) | Exotic (2)}
#   decimal_places  - integer
#   min_price       - decimal
#   max_price       - decimal
#   min_amount      - decimal
#   hidden          - integer
#   fee             - decimal
#   status          - enum { active (0) | archived (1) }
#
#  20.04.2022 ZT
################################################################################
class Pair < ApplicationRecord
  include ImagesHandleable
  
  belongs_to :base,  class_name: 'Coin'
  belongs_to :quote, class_name: 'Coin'

  enum level:  %w(Major Minor Exotic)
  enum status: %w(active archived)

  validates :base,  presence: true
  validates :quote, presence: true
  validates :name,  presence: true, uniqueness: true
  validates :code,  presence: true, uniqueness: true

  def set_pair_code
    "#{base.code}/#{quote.code}"
  end

  def set_pair_name
    "#{base.code.downcase}_#{quote.code.downcase}"
  end
end
  

app/controllers/admin/pairs_controller.rb
class Admin::PairsController < Admin::BaseController
  before_action :set_pair, only: [:show, :edit, :update,:destroy]
  after_action  :remove_images, only: :update

  def index
    @pairs = policy_scope(Pair)
  end

  def show
    authorize @pair
  end

  def new
    @pair = Pair.new
    authorize @pair
  end

  def edit
    authorize @pair
  end

  def create
    @pair = Pair.new(pair_params)
    authorize @pair
    if @pair.save
      redirect_to admin_pair_path(@pair), notice: t('messages.created', model: @pair.class.model_name.human)
    else      
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @pair
    if @pair.update(pair_params)
      redirect_to admin_pair_path(@pair), notice: t('messages.updated', model: @pair.class.model_name.human)
    else      
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @pair
    @pair.destroy
    flash[:success] = t('messages.deleted', model: @pair.class.model_name.human)
    redirect_to admin_pairs_path
  end

  private

    # Uses callbacks to share common setup or constraints between actions
    def set_pair
      @pair = Pair.find(params[:id])
    end

    # Removes images, selected during Editing
    def remove_images
      @pair.cover_image.purge if pair_params[:remove_cover_image] == '1'
      image_to_remove_ids = params['image_to_remove_ids']
      if image_to_remove_ids.present?
        image_to_remove_ids.each do |image_to_remove_id|
          @pair.images.find(image_to_remove_id).purge
        end
      end
    end

    # Only allows a trusted parameter 'white list' through
    def pair_params
      params.require(:pair).permit(
        :base_id, :quote_id, :name, :code, :level, :decimal_places, :min_price, :max_price, :min_amount, :hidden, :fee, :status, :cover_image, :remove_cover_image, images: []
      )
    end
end

app/views/admin/pairs/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-ms-6">
      <%=  simple_form_for([:admin, @pair], html: {multipart: true}) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.association :base, include_blank: false %>
          <%= f.association :quote, include_blank: false %>
          <%= f.input :name %>
          <%= f.input :code %>
          <%= f.input :level, include_blank: false %>
          <%= f.input :decimal_places %>
          <%= f.input :min_price %>
          <%= f.input :max_price %>
          <%= f.input :min_amount %>
          <%= f.input :hidden %>
          <%= f.input :fee %>
          <%= f.input :status, default: 0 %>
          <%#= render 'admin/shared/status_buttons', f: f %>
          <%= render 'admin/shared/form_images', f: f, object: @pair %>

          <%= render 'admin/shared/form_actions', f: f, object: @pair %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/pairs/_pair.html.erb
<div class='container'>
  <table class='table table-striped'>
    <tbody>
      <% @pair.attributes.each do |key, value| %>
        <tr>
          <% unless key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at' || key == 'updated_at' ||  key == 'cover_image_url' %>
            <% if key == 'status' %>
              <td><%= t 'status.status' %></td>
              <td><%= status_mark @pair.status %></td>
            <% else %>
              <td><%= t "activerecord.attributes.pair.#{key}" %></td>
              <td><%= value %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= render 'admin/shared/show_rich_text_content', object: @pair %>
  <%#= render 'admin/shared/show_images', object: @pair %>
</div>

app/views/admin/pairs/edit.html.erb
<h1><%= "#{t('actions.editing', model: @pair.class.model_name.human)}" %></h1>
<%= render 'form' %>

app/views/admin/pairs/index.html.erb
<h1><%= t Pair.model_name.human(count: 2) %></h1>
<table class='table table-hover'>
  <thead>
      <th><%= Pair.human_attribute_name(:base_id) %></th>
      <th><%= Pair.human_attribute_name(:quote_id) %></th>
      <th><%= Pair.human_attribute_name(:name) %></th>
      <th><%= Pair.human_attribute_name(:code) %></th>
      <th><%= Pair.human_attribute_name(:level) %></th>
      <th><%= Pair.human_attribute_name(:decimal_places) %></th>
      <th><%= Pair.human_attribute_name(:min_price) %></th>
      <th><%= Pair.human_attribute_name(:max_price) %></th>
      <th><%= Pair.human_attribute_name(:min_amount) %></th>
      <th><%= Pair.human_attribute_name(:hidden) %></th>
      <th><%= Pair.human_attribute_name(:fee) %></th>
      <th><%= Pair.human_attribute_name(:cover_image) %></th>
      <th><%= t 'status.status' %></th>
      <th><%= t 'actions.actions' %><th>
  </thead>

  <tbody>
    <% @pairs.each do |pair| %>
      <tr>
        <td><%= Coin.find(pair.base_id).code %></td>
        <td><%= Coin.find(pair.quote_id).code %></td>
        <td><%= pair.name %></td>
        <td><%= pair.code %></td>
        <td><%= pair.level %></td>
        <td><%= pair.decimal_places %></td>
        <td><%= pair.min_price %></td>
        <td><%= pair.max_price %></td>
        <td><%= pair.min_amount %></td>
        <td><%= pair.hidden %></td>
        <td><%= pair.fee %></td>
        <% if pair.cover_image.attached? %>
          <td><%= image_tag pair.cover_image.variant(resize_to_limit: [30, 30]) %></td>
        <% else %>
          <td></td>
        <% end %>        <td><%= status_mark pair.status %></td>
        <td><%= render 'admin/shared/index_buttons', resource: pair %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class='row'>
  <div class='col-md-2'>
    <%= link_to t('actions.create'), new_admin_pair_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

app/views/admin/pairs/new.html.erb
<h1><%= "#{t('actions.new', model: @pair.class.model_name.human)}" %></h1>
<%= render 'form' %>

app/views/admin/pairs/show.html.erb
<div class='container'>
  <p style='color: green'><%= notice %></p>
  <h1><%= t Pair.model_name.human %> <%= image_tag @pair.cover_image.variant(resize_to_limit: [70, 70]) %></h1>

  <%= render @pair %>
  <%= render 'admin/shared/show_actions', object: @pair %>
</div>